title: Greg Wilkinson
author: "Greg Wilkinson"

# theme: minima

remote_theme: jekyll/minima

plugins:
    - jekyll-remote-theme

base_url: /gwilkinson01.github.io
repository: gwilkinson01/gwilkinson01.github.io

# Minima social links
github_username: gwilkinson01
linkedin_username: gwilkinson01
rss: rss

# Minima: show excerpts in the frontpage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"
  skin: dark

# Minima: custom header links
header_pages:
  - _pages/frontpage.md
  - _pages/archive.md
  - _pages/about.md

include:
    - _pages

exclude: 
    - .gitignore
    - docker-compose.yml
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.md
